/**
 * LaTeX-to-Unicode symbol mappings for AMPL.
 *
 * Curated subset focused on mathematical optimization:
 * Greek letters, subscripts, superscripts, math operators,
 * set theory, arrows, and miscellaneous math symbols.
 */
export const latexSymbols: Record<string, string> = {
    // Greek lowercase
    '\\alpha': 'α',
    '\\beta': 'β',
    '\\gamma': 'γ',
    '\\delta': 'δ',
    '\\epsilon': 'ε',
    '\\varepsilon': 'ɛ',
    '\\zeta': 'ζ',
    '\\eta': 'η',
    '\\theta': 'θ',
    '\\vartheta': 'ϑ',
    '\\iota': 'ι',
    '\\kappa': 'κ',
    '\\lambda': 'λ',
    '\\mu': 'μ',
    '\\nu': 'ν',
    '\\xi': 'ξ',
    '\\pi': 'π',
    '\\varpi': 'ϖ',
    '\\rho': 'ρ',
    '\\varrho': 'ϱ',
    '\\sigma': 'σ',
    '\\varsigma': 'ς',
    '\\tau': 'τ',
    '\\upsilon': 'υ',
    '\\phi': 'φ',
    '\\varphi': 'ϕ',
    '\\chi': 'χ',
    '\\psi': 'ψ',
    '\\omega': 'ω',

    // Greek uppercase
    '\\Alpha': 'Α',
    '\\Beta': 'Β',
    '\\Gamma': 'Γ',
    '\\Delta': 'Δ',
    '\\Epsilon': 'Ε',
    '\\Zeta': 'Ζ',
    '\\Eta': 'Η',
    '\\Theta': 'Θ',
    '\\Iota': 'Ι',
    '\\Kappa': 'Κ',
    '\\Lambda': 'Λ',
    '\\Mu': 'Μ',
    '\\Nu': 'Ν',
    '\\Xi': 'Ξ',
    '\\Pi': 'Π',
    '\\Rho': 'Ρ',
    '\\Sigma': 'Σ',
    '\\Tau': 'Τ',
    '\\Upsilon': 'Υ',
    '\\Phi': 'Φ',
    '\\Chi': 'Χ',
    '\\Psi': 'Ψ',
    '\\Omega': 'Ω',

    // Subscript digits
    '\\_0': '₀',
    '\\_1': '₁',
    '\\_2': '₂',
    '\\_3': '₃',
    '\\_4': '₄',
    '\\_5': '₅',
    '\\_6': '₆',
    '\\_7': '₇',
    '\\_8': '₈',
    '\\_9': '₉',

    // Subscript operators
    '\\_+': '₊',
    '\\_-': '₋',
    '\\_=': '₌',
    '\\_(': '₍',
    '\\_)': '₎',

    // Subscript letters
    '\\_a': 'ₐ',
    '\\_e': 'ₑ',
    '\\_h': 'ₕ',
    '\\_i': 'ᵢ',
    '\\_j': 'ⱼ',
    '\\_k': 'ₖ',
    '\\_l': 'ₗ',
    '\\_m': 'ₘ',
    '\\_n': 'ₙ',
    '\\_o': 'ₒ',
    '\\_p': 'ₚ',
    '\\_r': 'ᵣ',
    '\\_s': 'ₛ',
    '\\_t': 'ₜ',
    '\\_u': 'ᵤ',
    '\\_v': 'ᵥ',
    '\\_x': 'ₓ',

    // Superscript digits
    '\\^0': '⁰',
    '\\^1': '¹',
    '\\^2': '²',
    '\\^3': '³',
    '\\^4': '⁴',
    '\\^5': '⁵',
    '\\^6': '⁶',
    '\\^7': '⁷',
    '\\^8': '⁸',
    '\\^9': '⁹',

    // Superscript operators
    '\\^+': '⁺',
    '\\^-': '⁻',
    '\\^=': '⁼',
    '\\^(': '⁽',
    '\\^)': '⁾',

    // Superscript letters
    '\\^a': 'ᵃ',
    '\\^b': 'ᵇ',
    '\\^c': 'ᶜ',
    '\\^d': 'ᵈ',
    '\\^e': 'ᵉ',
    '\\^f': 'ᶠ',
    '\\^g': 'ᵍ',
    '\\^h': 'ʰ',
    '\\^i': 'ⁱ',
    '\\^j': 'ʲ',
    '\\^k': 'ᵏ',
    '\\^l': 'ˡ',
    '\\^m': 'ᵐ',
    '\\^n': 'ⁿ',
    '\\^o': 'ᵒ',
    '\\^p': 'ᵖ',
    '\\^r': 'ʳ',
    '\\^s': 'ˢ',
    '\\^t': 'ᵗ',
    '\\^u': 'ᵘ',
    '\\^v': 'ᵛ',
    '\\^w': 'ʷ',
    '\\^x': 'ˣ',
    '\\^y': 'ʸ',
    '\\^z': 'ᶻ',

    // Math operators
    '\\sum': '∑',
    '\\prod': '∏',
    '\\coprod': '∐',
    '\\infty': '∞',
    '\\leq': '≤',
    '\\geq': '≥',
    '\\neq': '≠',
    '\\approx': '≈',
    '\\equiv': '≡',
    '\\pm': '±',
    '\\mp': '∓',
    '\\times': '×',
    '\\div': '÷',
    '\\cdot': '·',
    '\\star': '⋆',
    '\\circ': '∘',
    '\\bullet': '•',
    '\\oplus': '⊕',
    '\\ominus': '⊖',
    '\\otimes': '⊗',
    '\\oslash': '⊘',
    '\\odot': '⊙',
    '\\sqrt': '√',
    '\\cbrt': '∛',
    '\\lfloor': '⌊',
    '\\rfloor': '⌋',
    '\\lceil': '⌈',
    '\\rceil': '⌉',
    '\\langle': '⟨',
    '\\rangle': '⟩',

    // Comparison / ordering
    '\\ll': '≪',
    '\\gg': '≫',
    '\\le': '≤',
    '\\ge': '≥',
    '\\ne': '≠',
    '\\sim': '∼',
    '\\simeq': '≃',
    '\\cong': '≅',
    '\\propto': '∝',
    '\\prec': '≺',
    '\\succ': '≻',
    '\\preceq': '≼',
    '\\succeq': '≽',

    // Set theory
    '\\in': '∈',
    '\\notin': '∉',
    '\\ni': '∋',
    '\\subset': '⊂',
    '\\supset': '⊃',
    '\\subseteq': '⊆',
    '\\supseteq': '⊇',
    '\\cup': '∪',
    '\\cap': '∩',
    '\\emptyset': '∅',
    '\\varnothing': '∅',
    '\\setminus': '∖',

    // Logic
    '\\forall': '∀',
    '\\exists': '∃',
    '\\nexists': '∄',
    '\\neg': '¬',
    '\\land': '∧',
    '\\lor': '∨',
    '\\top': '⊤',
    '\\bot': '⊥',
    '\\vdash': '⊢',
    '\\models': '⊧',

    // Arrows
    '\\rightarrow': '→',
    '\\leftarrow': '←',
    '\\uparrow': '↑',
    '\\downarrow': '↓',
    '\\leftrightarrow': '↔',
    '\\Rightarrow': '⇒',
    '\\Leftarrow': '⇐',
    '\\Uparrow': '⇑',
    '\\Downarrow': '⇓',
    '\\Leftrightarrow': '⇔',
    '\\mapsto': '↦',
    '\\to': '→',
    '\\implies': '⟹',
    '\\iff': '⟺',
    '\\longmapsto': '⟼',
    '\\hookleftarrow': '↩',
    '\\hookrightarrow': '↪',

    // Calculus / analysis
    '\\partial': '∂',
    '\\nabla': '∇',
    '\\int': '∫',
    '\\iint': '∬',
    '\\iiint': '∭',
    '\\oint': '∮',

    // Miscellaneous math
    '\\degree': '°',
    '\\prime': '′',
    '\\dprime': '″',
    '\\ellipsis': '…',
    '\\cdots': '⋯',
    '\\vdots': '⋮',
    '\\ddots': '⋱',
    '\\hbar': 'ℏ',
    '\\ell': 'ℓ',
    '\\wp': '℘',
    '\\Re': 'ℜ',
    '\\Im': 'ℑ',
    '\\aleph': 'ℵ',

    // Blackboard bold (double-struck)
    '\\bbA': '𝔸',
    '\\bbB': '𝔹',
    '\\bbC': 'ℂ',
    '\\bbD': '𝔻',
    '\\bbE': '𝔼',
    '\\bbF': '𝔽',
    '\\bbG': '𝔾',
    '\\bbH': 'ℍ',
    '\\bbI': '𝕀',
    '\\bbJ': '𝕁',
    '\\bbK': '𝕂',
    '\\bbL': '𝕃',
    '\\bbM': '𝕄',
    '\\bbN': 'ℕ',
    '\\bbO': '𝕆',
    '\\bbP': 'ℙ',
    '\\bbQ': 'ℚ',
    '\\bbR': 'ℝ',
    '\\bbS': '𝕊',
    '\\bbT': '𝕋',
    '\\bbU': '𝕌',
    '\\bbV': '𝕍',
    '\\bbW': '𝕎',
    '\\bbX': '𝕏',
    '\\bbY': '𝕐',
    '\\bbZ': 'ℤ',
};
